all:
	gcc -g open-rump.c -o open-rump -lrump -lrumpuser -lrumpdev -lrumpdev_disk -lrumpdev_pci -lrumpdev_piixide -lrumpvfs -lrumpdev_scsipi

#-lrumpdev_drvctl

#-lrumpdev_ahcisata
	
#-lrumpdev_pci_virtio -lrumpdev_virtio_ld -lrumpdev_virtio_vioscsi
